DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "log";

CREATE TABLE "user"
(
    -- id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- id INTEGER PRIMARY KEY,
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE "log"
(
    -- id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- id INTEGER PRIMARY KEY,
    id SERIAL PRIMARY KEY,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    rating INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES "user" (id)
);